version: '3'
services:
  node1:
    image: blockchain
    container_name: node1
    build: .
    command: "node1 8000"
  node2:
    image: blockchain
    container_name: node2
    build: .
    command: "node2 8001"
  node3:
    image: blockchain
    container_name: node3
    build: .
    command: "node3 8002"